[package]
name = "runtime-module"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
libc = "0.2.171"
anyhow = "1.0.97"

[dev-dependencies]
tempfile = "3.19.1"
